package br.com.aco.DynamodbApp.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.springframework.data.annotation.Id;

import java.io.Serializable;
import java.time.Instant;
import java.time.LocalDate;
import java.util.Date;

@DynamoDBTable(tableName="Costumer")
public class Costumer implements Serializable {

    private static final long serialVersionUID = -4282005207341771716L;

    @Id
    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
//    @JsonIgnore
    private String id;

    @DynamoDBAttribute(attributeName = "company_name")
    @JsonProperty("company_name")
    private String companyName;

    @DynamoDBAttribute(attributeName = "company_document_number")
    @JsonProperty("company_document_number")
    private String companyDocumentNumber;

    @DynamoDBAttribute(attributeName = "phone_number")
    @JsonProperty("phone_number")
    private String phoneNumber;

    @DynamoDBAttribute(attributeName = "active")
    @JsonProperty("active")
    private Boolean active;

    @DynamoDBAttribute
    @DynamoDBTyped(DynamoDBMapperFieldModel.DynamoDBAttributeType.S)
    private LocalDate createdDate;

    @DynamoDBAttribute
    private Spec spec;

    public Costumer() {
    }

    public Costumer(
            String companyName,
            String companyDocumentNumber,
            String phoneNumber,
            Boolean active,
            Spec spec,
            LocalDate  createdDate
    ) {
        this.companyName = companyName;
        this.companyDocumentNumber = companyDocumentNumber;
        this.phoneNumber = phoneNumber;
        this.active = active;
        this.spec = spec;
        this.createdDate = createdDate;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getCompanyName() {
        return companyName;
    }

    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    public String getCompanyDocumentNumber() {
        return companyDocumentNumber;
    }

    public void setCompanyDocumentNumber(String companyDocumentNumber) {
        this.companyDocumentNumber = companyDocumentNumber;
    }

    public String getPhoneNumber() {
        return phoneNumber;
    }

    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    public Boolean getActive() {
        return active;
    }

    public void setActive(Boolean active) {
        this.active = active;
    }

    public Spec getSpec() {
        return spec;
    }

    public void setSpec(Spec spec) {
        this.spec = spec;
    }

    public LocalDate getCreatedDate() {
        return createdDate;
    }

    @DynamoDBTypeConvertedTimestamp(pattern="yyyyMMddHHmmssSSS", timeZone="UTC")
    public void setCreatedDate(LocalDate createdDate) {
        this.createdDate = createdDate;
    }
}
